/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Emits a collection of schemas that share one tailored helpers file.
 *
 * Each `emit` call produces one module in collection mode (helpers
 * referenced, never inlined) and accumulates the helper components that
 * module needs. After all members are emitted, `helpers()` yields the shared
 * helpers file containing exactly the union of accumulated needs — or null
 * when no member needed any helpers.
 */
export declare class CollectionSession {
  constructor(language: Language, options?: CollectionSessionOptions | undefined | null)
  /**
   * Emit one member module. `dirPrefix` is the relative path from the
   * module's output directory back to the collection root: "" (default) for
   * root-level files, one "../" per nesting level.
   */
  emit(schema: any, name?: string | undefined | null, dirPrefix?: string | undefined | null, options?: ConvertOptions | undefined | null): string
  /**
   * The shared helpers file name this session will use, or null for
   * languages that emit no runtime helpers.
   */
  helpersFileName(): string | null
  /** Helper component keys needed by all members emitted so far. */
  helperNeeds(): Array<string>
  /**
   * The tailored shared helpers file, or null when no member needed helpers
   * (no file should be written).
   */
  helpers(): HelpersFile | null
}

export interface CollectionSessionOptions {
  /** Custom helpers file name; defaults to the language's conventional name. */
  helpersFile?: string
  /** Emit mutable stored properties (see `TransformOptions#mutable`). */
  mutable?: boolean
}

export interface ConvertOptions {
  /**
   * Remote schema documents (URI → document) that non-fragment `$ref`s may
   * resolve against.
   */
  remotes?: Record<string, any>
  /** Enforce `format` during validation (default true). */
  enforceFormats?: boolean
}

/**
 * Conventional shared helpers file name for the language, or null for
 * languages that emit no runtime helpers.
 */
export declare function defaultHelpersFile(language: Language): string | null

/** File extension for the language's generated output (e.g. "zod.ts", "d.ts", "py"). */
export declare function extensionFor(language: Language): string

/**
 * Full content of the language's shared helpers file (a superset of every
 * possible need), or null when the language emits no runtime helpers. Prefer
 * `CollectionSession#helpers` which tailors the file to actual needs.
 */
export declare function helpersContent(language: Language): string | null

/** The shared helpers companion file for an emitted collection. */
export interface HelpersFile {
  fileName: string
  content: string
}

/** Convert a JSON Schema to a Kotlin data class. */
export declare function jsonSchemaToKotlin(schema: any, name?: string | undefined | null): string

/** Convert a JSON Schema to a Python Pydantic model. */
export declare function jsonSchemaToPydantic(schema: any, name?: string | undefined | null): string

/** Convert a JSON Schema to Rust serde types with validating deserialization. */
export declare function jsonSchemaToRust(schema: any, name?: string | undefined | null): string

/** Convert a JSON Schema to a Swift Codable struct. */
export declare function jsonSchemaToSwift(schema: any, name?: string | undefined | null): string

/** Convert a JSON Schema to TypeScript type definitions (.d.ts). */
export declare function jsonSchemaToTypescript(schema: any, name?: string | undefined | null): string

/** Convert a JSON Schema to a complete Zod TypeScript module string. */
export declare function jsonSchemaToZodModule(schema: any, name?: string | undefined | null): string

/** Target language/framework for generated output. */
export declare const enum Language {
  Zod = 'zod',
  TypeScript = 'typescript',
  Pydantic = 'pydantic',
  Swift = 'swift',
  Kotlin = 'kotlin',
  Rust = 'rust',
}

/**
 * Location of the shared helpers file relative to a generated module
 * (collection mode). Without this, helpers are inlined and the module is
 * self-contained.
 */
export interface SharedHelpersOptions {
  /** Helper file name at the collection root, e.g. "jst-helpers.ts". */
  fileName: string
  /**
   * Relative path prefix from the generated file's directory back to the
   * collection root: "" (default) for root-level files, one "../" per
   * nesting level.
   */
  dirPrefix?: string
}

/** Convert a JSON Schema to generated code for the given target language. */
export declare function transform(schema: any, language: Language, options?: TransformOptions | undefined | null): string

export interface TransformOptions {
  /**
   * Generated root type name (PascalCased). Falls back to the schema's root
   * `title`; errors when neither is available.
   */
  name?: string
  /**
   * Emit mutable stored properties (Swift `var`, Kotlin `var`; Pydantic
   * enables assignment re-validation). No-op for Rust and TypeScript/Zod.
   */
  mutable?: boolean
  /**
   * Collection mode: reference helpers from a shared companion file instead
   * of inlining them. Prefer `CollectionSession` which also tailors the
   * helpers file to what the emitted modules actually need.
   */
  helpers?: SharedHelpersOptions
  /**
   * Remote schema documents (URI → document) that non-fragment `$ref`s may
   * resolve against.
   */
  remotes?: Record<string, any>
  /**
   * Enforce `format` during validation (default true). Draft 2020-12 treats
   * `format` as annotation-only; set false for that behavior.
   */
  enforceFormats?: boolean
}
